### ISSUE TITLE
Broken API

### ISSUE THREAD

**Issue by kofronpi** [zavan/google_maps_api-distance_matrix#2]
Hi !

I'm using rails 4.2.6 with Ruby 2.3.0
When attempting to use your gem from rails console:
```

origins = [[2.85800005014191, 50.4953248662245]] 
destinations =  [[2.85773780193996, 50.49494146317214], [2.854084019245316, 50.48937560068271], [2.867151912465668, 50.495960836073216]] 
options = { key: 'my-api-key', https: true }

```

It fails:
```
2.3.0 :015 > GoogleMapsAPI::DistanceMatrix.calculate(origins, destinations, options)
NoMethodError: undefined method `[]' for nil:NilClass
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-core-0.2.0/lib/google_maps_api/core/metric.rb:18:in `from_hash'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/element.rb:13:in `from_hash'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/row.rb:16:in `block in build_elements'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/row.rb:15:in `collect'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/row.rb:15:in `build_elements'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/row.rb:9:in `from_hash'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/response.rb:34:in `block in build_rows'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/response.rb:33:in `collect'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/response.rb:33:in `build_rows'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/response.rb:16:in `from_json'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix/request.rb:25:in `perform'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/google_maps_api-distance_matrix-0.2.1/lib/google_maps_api/distance_matrix.rb:13:in `calculate'
  from (irb):15
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
... 7 levels...
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/spring-1.6.4/lib/spring/commands/rails.rb:6:in `call'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/spring-1.6.4/lib/spring/command_wrapper.rb:38:in `call'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:185:in `block in serve'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:156:in `fork'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:156:in `serve'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:131:in `block in run'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `loop'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/spring-1.6.4/lib/spring/application.rb:125:in `run'
  from /home/kofronpi/myfolder/myproject/.bundle/ruby/2.3.0/gems/spring-1.6.4/lib/spring/application/boot.rb:18:in `<top (required)>'
  from /home/kofronpi/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/kofronpi/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from -e:1:in `<main>'2.3.0 :016 > 

```

**Comment by zavan** [comment]
Hi!

Thank you for pointing this out.

This happens when the API can't find the distance between any origin-destination pair, see:

https://maps.googleapis.com/maps/api/distancematrix/json?origins=2.85800005014191,%2050.4953248662245&destinations=2.85773780193996,%2050.49494146317214|2.854084019245316,50.48937560068271|2.867151912465668,%2050.495960836073216

```json
{
   "destination_addresses" : [
      "2.85773780193996,50.49494146317214",
      "2.8540840192453159,50.489375600682713",
      "2.8671519124656681,50.495960836073216"
   ],
   "origin_addresses" : [ "2.85800005014191,50.4953248662245" ],
   "rows" : [
      {
         "elements" : [
            {
               "status" : "ZERO_RESULTS"
            },
            {
               "status" : "ZERO_RESULTS"
            },
            {
               "status" : "ZERO_RESULTS"
            }
         ]
      }
   ],
   "status" : "OK"
}
```

I'll  fix it later today.

**Comment by zavan** [comment]
0.2.2 released with a fix for this. 
Thanks again.
